book/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path("",views.BookListView.as_view(),name="list"),
    path("<slug:slug>/", views.BookDetailView.as_view(), name="detail"),


    #demo how to use string
    #path("test/<str:url_string>/", views.test, name="test"),

    path("check_book/<slug:url_string>/", views.check_book, name="check_book"),
    path("check_bookp/<slug:url_string>/", views.check_bookp, name="check_bookp"),
    path("gen_token/<slug:booktoken>/", views.gen_token, name="gen_token"),
    path("gen_tokenp/<slug:booktoken>/", views.gen_tokenp, name="gen_tokenp"),
	path("undo/<slug:booki>/", views.undo, name="undo"),
	path("reviews/<slug:bookn>/", views.reviews, name="reviews"),


]

bookcafe/urls.py
from django.contrib import admin
from django.urls import include,path

from .import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from . import views
from accounts.views.views import  LoginView


urlpatterns = [
    path("",views.home,name="home"),
    #path("home",views.home,name="home1"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),#accounts:logout


    path('admin/', admin.site.urls),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('category/', include(('category.urls', 'category'), namespace='category')),

    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('account/', include('accounts.passwords.urls')),
    path('search/', include(('search.urls', 'search'), namespace='search')),


#    path('cat1books/', include(('cat1books.urls', 'cat1books'), namespace='cat1books')),

    # notification part
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),

    path('donation/', include(('donation.urls', 'donation'), namespace='donation')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls','payment')),
    # path('paypal/',include('paypal.standard.ipn.urls')),
    # path('payment/',include('payment.urls','payment')),

    path('tokena/', include(('tokena.urls', 'tokena'), namespace='tokena')),

    path('del_borrower/', include(('del_borrower.urls', 'del_borrower'), namespace='del_borrower')),

    #path('feedback/', include('feedback_form.urls')),
    path('feedback/', include(('feedback_form.urls', 'feedback'), namespace='feedback')),
    path('contact/', include(('contactus.urls', 'contact'), namespace='contact')),

#     path('contactus/', include('contactus.urls'))
# submit
]

if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tokena/urls.py
from django.contrib import admin
from django.urls import include,path

from . import views

urlpatterns = [
    path("",views.disp_tokens,name="disp_tokens"),
    # path("adduser",views.adduser,name="adduser"),
    path("<int:tokenNo>/", views.add_book, name="add_book"),

]

tokena/models.py
from django.db import models

# Create your models here.

tokena/views.py
from django.shortcuts import render,redirect

# Create your views here.
from borrower.models import token
from events.models import borrower_detail

from django.contrib.admin.views.decorators import staff_member_required


@staff_member_required
def disp_tokens(request):
	context={"tokens":token.objects.all()}
	return render(request,"tokena/ad.html",context)


def add_book(request,tokenNo):

	t=token.objects.get(token=tokenNo)
	

	user=t.user
	book=t.book
	date=t.date
	rdate=t.rdate


	if t.user2 and t.user3:
		user2=t.user2
		user3=t.user3
		b=borrower_detail.objects.create(name=user,book_name=book,issue_date=date,submission_date=rdate)
		b.pooled_users.add(user2)
		b.pooled_users.add(user3)

	else:	
		b=borrower_detail.objects.create(name=user,book_name=book,issue_date=date,submission_date=rdate)


	t.deleted=True
	t.save()
	print(rdate)
	# b.book_name.add(book)
	b.save()

	return redirect("tokena:disp_tokens")

tokena/templates/tokena/ad.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>

	#mydiv
		 { 
  			width: 100%;
  			height:100%;
  			background-repeat: no-repeat;
  			background-image: url(https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiDx9a8pJrfAhUfT48KHSwWAUIQjRx6BAgBEAU&url=https%3A%2F%2Fpngtree.com%2Ffreebackground%2Fbooks-background_237809.html&psig=AOvVaw3LaL8L_w3V9oRb4b40xGFj&ust=1544703850010862)
  			background-blend-mode:lighten;
         }
	
		table {
             	font-family: sans-serif;
             	border-collapse: collapse;
              	width: 50%;
              	margin-top:150px;
  				margin-bottom:150px;
  				margin-left: 200px;
              }
        td, th {
  				
  				text-align: left;
  				padding: 8px;
  				margin-top:60px;
  				margin-bottom:150px;
  				margin-left: 500px;
               }



	</style>
</head>
<body><div class=#mydiv></div>
	<center>
<table>
{% for t in tokens %}
	{% if not t.deleted %}
	<tr><th>TOKENS</th>
		<th>REQUEST</th>
	</tr>
	<tr>
	<td>token No. :: {{ t.token }}</td>
	<td>
	<form  method='POST' > {% csrf_token %}
	<button type='submit' formaction="{% url 'tokena:add_book' t.token %}" >Request to issue</button>
	</form>
    </td>
	</tr>
	<br>
{% endif %}

{% endfor %}
</table>
</center>
</body>
</html>